require "rails_helper"
require "legacy_activity"

RSpec.describe LegacyActivity do
  let(:activity_node_set) do
    Nokogiri::XML(
      File.read("#{Rails.root}/spec/fixtures/activities/uksa/single_activity.xml"),
      nil,
      "UTF-8"
    ).xpath("//iati-activity").first
  end

  describe "#elements" do
    it "returns the nokogiri nodes for this document" do
      result = described_class.new(activity_node_set: activity_node_set).elements
      expect(result.class).to eql(Nokogiri::XML::NodeSet)
    end
  end

  describe "#to_xml" do
    it "returns the xml representation for this document" do
      legacy_xml = File.read("#{Rails.root}/spec/fixtures/activities/uksa/individual_activity.xml")

      result = described_class.new(activity_node_set: activity_node_set).to_xml

      expect(result.squish).to eql(legacy_xml.squish)
    end
  end

  describe "#identifier" do
    context "when there is an identifier element" do
      it "returns the full IATI identifier" do
        activity_xml = <<~XML
          <?xml version="1.0" encoding="UTF-8"?>
          <iati-activities generated-datetime="2019-09-25T22:01:44.470000+00:00" version="2.03">
            <!--Data generated by IATI CoVE. Built by Open Data Services Co-operative: http://iati.cove.opendataservices.coop/-->
            <iati-activity default-currency="GBP" hierarchy="2" last-updated-datetime="2019-09-25T22:01:44.470000+00:00">
              <iati-identifier>GB-GOV-13-GCRF-UKSA_NS_UKSA-019</iati-identifier>
            </iati-activity>
          </iati-activities>
        XML

        activity_node_set = Nokogiri::XML(activity_xml, nil, "UTF-8").xpath("//iati-activity").first

        result = described_class.new(activity_node_set: activity_node_set)
        expect(result.identifier).to eql("GB-GOV-13-GCRF-UKSA_NS_UKSA-019")
      end
    end

    context "when there is no identifier element" do
      it "returns nil" do
        activity_xml = <<~XML
          <?xml version="1.0" encoding="UTF-8"?>
          <iati-activities generated-datetime="2019-09-25T22:01:44.470000+00:00" version="2.03">
            <!--Data generated by IATI CoVE. Built by Open Data Services Co-operative: http://iati.cove.opendataservices.coop/-->
            <iati-activity default-currency="GBP" hierarchy="2" last-updated-datetime="2019-09-25T22:01:44.470000+00:00">
            </iati-activity>
          </iati-activities>
        XML

        activity_node_set = Nokogiri::XML(activity_xml, nil, "UTF-8").xpath("//iati-activity").first

        result = described_class.new(activity_node_set: activity_node_set)
        expect(result.identifier).to eq(nil)
      end
    end
  end
end
