#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -z "$CI" ]; then
  if [ -f Brewfile ] && [ "$(uname -s)" = "Darwin" ]; then
    if ! brew bundle check >/dev/null 2>&1; then
      echo "==> Installing Homebrew dependencies..."
      brew bundle install --verbose --no-lock
    fi
  fi

  if [ -f .ruby-version ]; then
    eval "$(rbenv init -)"

    if [ -z "$(rbenv version-name 2>/dev/null)" ]; then
      echo "==> Installing Ruby..."
      rbenv install --skip-existing
      rbenv rehash
    fi
  fi
fi

if ! command -v bundle >/dev/null 2>&1; then
  echo "==> Installing Bundler..."
  gem install bundler

  if [ -z "$CI" ]; then
    rbenv rehash
  fi
fi

if ! bundle check >/dev/null 2>&1; then
  echo "==> Installing Ruby dependencies..."
  bundle install
fi

if [ -f package.json ]; then
  if ! yarn check --verify-tree >/dev/null 2>&1; then
    echo "==> Installing JS dependencies..."
    yarn install
  fi
fi

REDIS_STATUS=$(redis-cli ping)

if [ "$REDIS_STATUS" != "PONG" ]; then
  echo "===> Starting Redis server in daemon mode"
  redis-server /usr/local/etc/redis.conf --daemonize yes
fi
