#!/bin/sh

set -e

docker-compose -f docker-compose.test.yml build
docker-compose -f docker-compose.test.yml run \
  -e CI=true \
  -e COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" \
  test script/test
