#!/bin/bash

# script/db-restore: Restore the local database from staging/production.

set -e

ORGANISATION_NAME="beis-report-official-development-assistance"
ENVIRONMENT_NAME="${1:-staging}"
environments="pentest prod staging"

# Check `ENVIRONMENT_NAME` is one we expect
if ! echo "$environments"| grep -w "$ENVIRONMENT_NAME" > /dev/null; then
    echo "The environment name must be one of the following: $environments"
    exit 1
fi

# Make sure we're in the root of the project
cd "$(dirname "$0")/.."

# Check prerequisites are installed
if ! command -v cf > /dev/null; then
    echo "The Cloud Foundry (cf) tool is not installed. See https://docs.cloud.service.gov.uk/get_started.html#set-up-the-cloud-foundry-command-line for how to get started"
    exit 1
fi

if ! cf plugins | grep -q "conduit"; then
    echo "The cf conduit plugin is not installed. See https://github.com/UKGovernmentBEIS/beis-report-official-development-assistance/blob/develop/doc/database-backup-and-restore.md#installing-the-cf-conduit-plugin for installation instructions."
    exit 1
fi

# exit with this by default, if it is not set later
exit_code=0

# Create a unique filename, so we can delete it later
timestamp=$(date +"%Y%m%d%I%M%S")
filename="/tmp/dump-$timestamp.tar"

# Cleanup on exit, no matter what happens
cleanup () {
    echo "==> Cleaning up..."
    rm "$filename" &> /dev/null
    exit "$exit_code"
}

# register the cleanup function for all these signal types
trap cleanup EXIT ERR INT TERM

echo "==> Logging into GOV.UK PaaS..."

if ! cf target -o "$ORGANISATION_NAME" -s "$ENVIRONMENT_NAME" &>/dev/null;  then
  cf login -o "$ORGANISATION_NAME" -s "$ENVIRONMENT_NAME"
fi

# Set the Postgres service name, depending on our environment
service="beis-roda-${ENVIRONMENT_NAME}-postgres"

# Check the user wants to continue before blowing away the development data
echo "THIS WILL DELETE ALL DATA IN YOUR DEVELOPMENT ENVIRONMENT."
echo "Are you sure you want to continue? (y to continue)"
read -p "" -r delete_data

if [ "$delete_data" == "y" ]; then
    echo "==> Running pg_dump on ${service} on ${ENVIRONMENT_NAME}"
    cf conduit "$service" -- \
        pg_dump \
            --file "$filename" \
            --no-acl \
            --no-owner \
            --format=t \
            --exclude-table-data="users" \
            --exclude-table="ar_internal_metadata" \
            --exclude-table="spatial_ref_sys"

    echo "==> Dropping and recreating the roda-development database..."
    psql -c '\set AUTOCOMMIT on\n DROP DATABASE IF EXISTS "roda-development"; CREATE DATABASE "roda-development";' -d postgres

    echo "==> Restoring the data from the backup..."
    pg_restore -d roda-development --no-owner --clean "$filename" || true

    echo "==> Removing extraneous Postgres extensions..."
    psql -d roda-development -c 'DROP EXTENSION IF EXISTS citext; DROP EXTENSION IF EXISTS postgis; DROP EXTENSION IF EXISTS "uuid-ossp";'

    echo "==> Setting database environment..."
    bundle exec rails db:environment:set RAILS_ENV=development

    echo "==> Running database migrations..."
    bundle exec rails db:migrate

    echo "==> Seeding development users..."
    bundle exec rails runner 'load File.join(Rails.root, "db", "seeds", "development_users.rb")'
fi

exit_code=$?
