#!/bin/bash
# script to deploy terraform
# exit on error or if a variable is unbound
set -eu

# Disable the shellcheck check for unassigned variables. We export this var
# in Github Actions, but Shellcheck complains because there are lowercase
# characters in it

# shellcheck disable=2154
echo "deploying $TF_VAR_environment"

cd terraform

# deploy terraform using tfenv
if [ ! -e ~/.tfenv ]
then
git clone https://github.com/tfutils/tfenv.git ~/.tfenv
fi
export PATH="$HOME/.tfenv/bin:$PATH"
tfenv install

../install-terraform-provider-for-cf.sh

# CF_PASSWORD, CF_USER, AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID
# must be set for the following commands to run

# initialise terraform
terraform init

# select the correct workspace
terraform workspace select "$TF_VAR_environment"

# apply the terraform
terraform apply -auto-approve

echo "$TF_VAR_environment has been deployed"
