#!/bin/bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build --target web -t "thedxw/beis-report-official-development-assistance:$DOCKER_TAG" .
docker push "thedxw/beis-report-official-development-assistance:$DOCKER_TAG"
