name: CI

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create coverage directory
        run: mkdir -p ./coverage
      - name: Run tests
        run: script/cibuild
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: ./coverage/lcov.info
          fail-on-error: false
