name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6.3"
      - name: Set up Docker
        run: docker network create test
      - name: Set up Postgres
        run: docker run -d --name pg --network test -e POSTGRES_USER=test -p 5432:5432 postgres:11
      - name: Build a new Docker image
        run: docker build . --build-arg RAILS_ENV=test -t app:test
      - name: Set up a new container for testing
        run: |
          docker run -d --name test-container \
            --network test \
            -e RAILS_ENV=test \
            -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true \
            -e DATABASE_URL=postgres://test@pg:5432/app_test \
            app:test /bin/bash -c "tail -f /dev/null"
      - name: Run the tests
        run: docker exec test-container rake